# Generated by Django 2.0 on 2021-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='firstname', max_length=255)),
                ('lname', models.CharField(default='lasttname', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwd', models.CharField(default='password', max_length=255)),
            ],
        ),
    ]
